version: '3'
services:
  kafka-kraft:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-kraft
    ports:
      - "9101:9101"
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-kraft:29092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_JMX_PORT=9101
      - KAFKA_JMX_HOSTNAME=localhost
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka-kraft:29093
      - KAFKA_LISTENERS=PLAINTEXT://kafka-kraft:29092,CONTROLLER://kafka-kraft:29093,PLAINTEXT_HOST://0.0.0.0:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qk
    volumes:
      - ./kafka-kraft-data:/var/lib/kafka/data
    networks:
      - kafka-network

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    hostname: schema-registry
    environment:
      - SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=PLAINTEXT://kafka-kraft:29092
      - SCHEMA_REGISTRY_HOST_NAME=localhost
      - SCHEMA_REGISTRY_LISTENERS=http://localhost:8081
      - SCHEMA_REGISTRY_DEBUG=true
    ports:
      - "8081:8081"
    depends_on:
      - kafka-kraft
    volumes:
      - ./schema-registry-data:/var/lib/schema-registry
    networks:
      - kafka-network

  kafka-rest:
    image: confluentinc/cp-kafka-rest:latest
    hostname: kafka-rest
    environment:
      - KAFKA_REST_BOOTSTRAP_SERVERS=kafka-kraft:29092
      - KAFKA_REST_SCHEMA_REGISTRY_URL=http://schema-registry:8081
      - KAFKA_REST_LISTENERS=http://kafka-rest:8082
      # KAFKA_REST_HOST_NAME: rest-proxy
      # KAFKA_REST_LISTENERS: "http://0.0.0.0:8082"
      # KAFKA_REST_BOOTSTRAP_SERVERS: $BOOTSTRAP_SERVERS
      # KAFKA_REST_SECURITY_PROTOCOL: "$SECURITY_PROTOCOL"
      # KAFKA_REST_SASL_JAAS_CONFIG: $SASL_JAAS_CONFIG
      # KAFKA_REST_SASL_MECHANISM: "PLAIN"
      # KAFKA_REST_CLIENT_BOOTSTRAP_SERVERS: $BOOTSTRAP_SERVERS
      # KAFKA_REST_CLIENT_SECURITY_PROTOCOL: "SASL_SSL"
      # KAFKA_REST_CLIENT_SASL_JAAS_CONFIG: $SASL_JAAS_CONFIG
      # KAFKA_REST_CLIENT_SASL_MECHANISM: "PLAIN"
    ports:
      - "8082:8082"
    depends_on:
      - kafka-kraft
      - schema-registry
    volumes:
      - ./kafka-rest-data:/var/lib/kafka-rest
    networks:
      - kafka-network

networks:
  kafka-network:

# mkdir kafka-kraft-data schema-registry-data kafka-rest-data
